language: go

go:
  - 1.1
  - 1.2
  - tip

before_script:
- go get github.com/stretchr/testify/assert

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get code.google.com/p/go.tools/cmd/cover
  
script:
    - $HOME/gopath/bin/goveralls -repotoken mz4jKJxZrn6hWPZF5D8Sw69674QYJCixS
